# Utilisation d'une image de base avec Java
FROM openjdk:11-jre-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier de dépendances (pom.xml pour Maven)
COPY pom.xml .

# Télécharger et installer les dépendances
RUN mvn -B dependency:go-offline

# Copier les sources de l'application
COPY src ./src

# Construire l'application
RUN mvn -B package -DskipTests

# Commande pour exécuter l'application
CMD ["java", "-jar", "target/car.jar"]
